# Site settings
title: Code for Münster
email: muenster@codefor.de
description: > # this means to ignore newlines until "baseurl:"
  Jede Woche treffen sich in ganz Deutschland „Code for Germany“ Teams, die gemeinsam an nützlichen Anwendungen und Visualisierungen rund um offene Daten und digitale Werkzeuge für Bürgerinnen arbeiten.
  Lokale Gruppen, bestehend aus Programmiererinnen, Designern und Open Data Interessierten, erproben, wie Code und Software dabei helfen können ihre Stadt und Nachbarschaft zu verbessern.
  Auch in Münster besteht seit einem Jahr eine Gruppe aus interessierten Nutzern, die sich „Code for Münster“ nennt.
baseurl: "" # the subpath of your site, e.g. /blog, change when you fork the repo from Code for Münster!
url: "codeformuenster.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  smart_quotes: ["sbquo", "lsquo", "bdquo", "ldquo"]
permalink: /:categories/:year/:month/:day/:title/
keywords:
  - "Münster"
  - "Open Data"
  - "Offene Daten"
  - "Code"
  - "Code for Münster"
  - "E-Government"
  - "Transparenz"
  - "Bürgerbeteiligung"
  - "Stadtentwicklung"
  - "Visualisierung"
  - "Stadt"
  - "Demokratie"
repository: codeformuenster/codeformuenster.github.io
remote_theme: chrisrhymes/bulma-clean-theme@eb8d08e78e150b4dc5dd37742cb9f6237e0b46a7
plugins:
  - jekyll-feed

footer_menu: footer_links

# gem jekyll-seo-tag
twitter:
  username: codeformuenster
  card: summary
author:
  twitter: codeformuenster
social:
  name: Code for Münster
  links:
    - https://twitter.com/codeformuenster
    - https://github.com/codeformuenster
lang: de_DE

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
